/* Generated by color-variables-plugin */
export enum ColorEnum {
  THEME_LIGHT = '#ffffff',
  THEME_DARK = '#1f2128',
  PRIMARY_COLOR = '#6c5dd3',
  ERROR_COLOR = '#ff754c',
  TEXT_COLOR = '#11142d',
  TEXT_COLOR_INVERSE = '#ffffff',
  CAPTION_COLOR = '#808191'
}
